In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
pd.__version__

'0.24.2'

In [21]:
mappings = {
'India':1,
'Australia':2,
'England':3,
'South Africa':4,
'New Zealand':5,
'Pakistan':6,
'West Indies':7,
'Sri Lanka':8,
'Bangladesh':9,
'Afganistan':10
}

In [22]:
data = pd.read_excel (r'C:\Users\Dhruv\Desktop\WC.xlsx')

In [23]:
data

Team 1        Team 2        Team 3        Team 4        Winner
0           India  South Africa       England     Australia     Australia
1           India     Australia       England      Pakistan       England
2     New Zealand     Australia  South Africa       England   New Zealand
3         England   New Zealand         India     Australia         India
4    South Africa         India   New Zealand     Australia  South Africa
5        Pakistan     Australia       England         India       England
6     New Zealand  South Africa       England     Australia     Australia
7    South Africa         India       England     Australia  South Africa
8     New Zealand  South Africa         India       England  South Africa
9           India       England     Australia  South Africa         India
10    New Zealand       England         India     Australia         India
11        England   West Indies     Australia         India         India
12          India     Australia       England   New Zealand         India
13        England         India     Australia  South Africa       England
14    West Indies     Australia         India       England         India
15          India       England     Australia   New Zealand   New Zealand
16   South Africa         India   New Zealand       England  South Africa
17        England  South Africa   West Indies         India         India
18      Australia   New Zealand         India       England       England
19        England         India     Australia  South Africa       England
20    West Indies     Australia         India       England         India
21          India       England     Australia   New Zealand   New Zealand
22        England   West Indies     Australia         India         India
23       Pakistan     Australia       England         India       England
24    West Indies     Australia         India       England         India
25          India     Australia       England      Pakistan       England
26      Australia   West Indies   New Zealand  South Africa  South Africa
27          India     Australia       England   New Zealand         India
28        England         India     Australia  South Africa       England
29    West Indies     Australia         India       England         India
..            ...           ...           ...           ...           ...
81   South Africa         India       England     Australia  South Africa
82    New Zealand  South Africa         India       England  South Africa
83          India       England     Australia  South Africa         India
84    New Zealand       England         India     Australia         India
85        England   West Indies     Australia         India         India
86          India     Australia       England   New Zealand         India
87        England         India     Australia  South Africa       England
88    West Indies     Australia         India       England         India
89          India       England     Australia   New Zealand   New Zealand
90   South Africa         India   New Zealand       England  South Africa
91        England  South Africa   West Indies         India         India
92      Australia   New Zealand         India       England       England
93        England         India     Australia  South Africa       England
94    West Indies     Australia         India       England         India
95          India       England     Australia   New Zealand   New Zealand
96        England   West Indies     Australia         India         India
97       Pakistan     Australia       England         India       England
98    West Indies     Australia         India       England         India
99          India     Australia       England      Pakistan       England
100     Australia   West Indies   New Zealand  South Africa  South Africa
101         India     Australia       England   New Zealand         India
102       England         India     Australia  South Africa       England
103   West Indi

In [24]:
df = pd.DataFrame(data)
df.index = np.arange(1, len(df)+1)
array_of_cols = df.columns.values
for x in array_of_cols:
    df[x].replace(mappings, inplace=True)
df

Team 1 Team 2 Team 3 Team 4 Winner
1        1      4      3      2      2
2        1      2      3      6      3
3        5      2      4      3      5
4        3      5      1      2      1
5        4      1      5      2      4
6        6      2      3      1      3
7        5      4      3      2      2
8        4      1      3      2      4
9        5      4      1      3      4
10       1      3      2      4      1
11       5      3      1      2      1
12       3      7      2      1      1
13       1      2      3      5      1
14       3      1      2      4      3
15       7      2      1      3      1
16       1      3      2      5      5
17       4      1      5      3      4
18       3      4      7      1      1
19       2      5      1      3      3
20       3      1      2      4      3
21       7      2      1      3      1
22       1      3      2      5      5
23       3      7      2      1      1
24       6      2      3      1      3
25       7      2      1      3      1
26       1      2      3      6      3
27       2      7      5      4      4
28       1      2      3      5      1
29       3      1      2      4      3
30       7      2      1      3      1
..     ...    ...    ...    ...    ...
82       4      1      3      2      4
83       5      4      1      3      4
84       1      3      2      4      1
85       5      3      1      2      1
86       3      7      2      1      1
87       1      2      3      5      1
88       3      1      2      4      3
89       7      2      1      3      1
90       1      3      2      5      5
91       4      1      5      3      4
92       3      4      7      1      1
93       2      5      1      3      3
94       3      1      2      4      3
95       7      2      1      3      1
96       1      3      2      5      5
97       3      7      2      1      1
98       6      2      3      1      3
99       7      2      1      3      1
100      1      2      3      6      3
101      2      7      5      4      4
102      1      2      3      5      1
103      3      1      2      4      3
104      7      2      1      3      1
105      1      3      2      5      5
106      4      1      5      3      4
107      3      4      7      1      1
108      2      5      1      3      3
109      3      1      2      4      3
110      7      2      1      3      1
111      1      3      2      5      5

[111 rows x 5 columns]

In [25]:
df_X = df.loc[:,'Team 1':'Team 4']
df_Y = df.loc[:,'Winner']
X = df_X.to_numpy()
Y = df_Y.to_numpy()

In [26]:
X = X.astype('int')
X

array([[1, 4, 3, 2],
       [1, 2, 3, 6],
       [5, 2, 4, 3],
       [3, 5, 1, 2],
       [4, 1, 5, 2],
       [6, 2, 3, 1],
       [5, 4, 3, 2],
       [4, 1, 3, 2],
       [5, 4, 1, 3],
       [1, 3, 2, 4],
       [5, 3, 1, 2],
       [3, 7, 2, 1],
       [1, 2, 3, 5],
       [3, 1, 2, 4],
       [7, 2, 1, 3],
       [1, 3, 2, 5],
       [4, 1, 5, 3],
       [3, 4, 7, 1],
       [2, 5, 1, 3],
       [3, 1, 2, 4],
       [7, 2, 1, 3],
       [1, 3, 2, 5],
       [3, 7, 2, 1],
       [6, 2, 3, 1],
       [7, 2, 1, 3],
       [1, 2, 3, 6],
       [2, 7, 5, 4],
       [1, 2, 3, 5],
       [3, 1, 2, 4],
       [7, 2, 1, 3],
       [1, 3, 2, 5],
       [4, 1, 5, 3],
       [3, 4, 7, 1],
       [2, 5, 1, 3],
       [3, 1, 2, 4],
       [7, 2, 1, 3],
       [1, 3, 2, 5],
       [1, 4, 3, 2],
       [1, 2, 3, 6],
       [5, 2, 4, 3],
       [3, 5, 1, 2],
       [4, 1, 5, 2],
       [6, 2, 3, 1],
       [5, 4, 3, 2],
       [4, 1, 3, 2],
       [5, 4, 1, 3],
       [1, 3, 2, 4],
       [5, 3,

In [27]:
Y = Y.astype('int')
Y

array([2, 3, 5, 1, 4, 3, 2, 4, 4, 1, 1, 1, 1, 3, 1, 5, 4, 1, 3, 3, 1, 5,
       1, 3, 1, 3, 4, 1, 3, 1, 5, 4, 1, 3, 3, 1, 5, 2, 3, 5, 1, 4, 3, 2,
       4, 4, 1, 1, 1, 1, 3, 1, 5, 4, 1, 3, 3, 1, 5, 1, 3, 1, 3, 4, 1, 3,
       1, 5, 4, 1, 3, 3, 1, 5, 2, 3, 5, 1, 4, 3, 2, 4, 4, 1, 1, 1, 1, 3,
       1, 5, 4, 1, 3, 3, 1, 5, 1, 3, 1, 3, 4, 1, 3, 1, 5, 4, 1, 3, 3, 1,
       5])

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, random_state=0)

In [29]:
X_train

array([[1, 3, 2, 5],
       [5, 4, 3, 2],
       [3, 7, 2, 1],
       [3, 4, 7, 1],
       [4, 1, 5, 3],
       [3, 7, 2, 1],
       [1, 3, 2, 5],
       [3, 1, 2, 4],
       [1, 2, 3, 5],
       [2, 5, 1, 3],
       [2, 7, 5, 4],
       [1, 3, 2, 5],
       [4, 1, 5, 2],
       [5, 4, 1, 3],
       [3, 7, 2, 1],
       [1, 3, 2, 5],
       [1, 2, 3, 6],
       [7, 2, 1, 3],
       [6, 2, 3, 1],
       [4, 1, 5, 2],
       [4, 1, 5, 2],
       [1, 3, 2, 5],
       [3, 4, 7, 1],
       [3, 5, 1, 2],
       [1, 2, 3, 6],
       [6, 2, 3, 1],
       [4, 1, 5, 3],
       [1, 2, 3, 5],
       [4, 1, 5, 3],
       [1, 4, 3, 2],
       [3, 1, 2, 4],
       [3, 1, 2, 4],
       [2, 5, 1, 3],
       [3, 1, 2, 4],
       [3, 7, 2, 1],
       [1, 2, 3, 6],
       [7, 2, 1, 3],
       [6, 2, 3, 1],
       [4, 1, 5, 3],
       [3, 1, 2, 4],
       [7, 2, 1, 3],
       [5, 3, 1, 2],
       [7, 2, 1, 3],
       [3, 4, 7, 1],
       [3, 1, 2, 4],
       [7, 2, 1, 3],
       [1, 2, 3, 6],
       [3, 1,

In [30]:
X_test

array([[1, 2, 3, 6],
       [5, 3, 1, 2],
       [5, 2, 4, 3],
       [5, 2, 4, 3],
       [7, 2, 1, 3],
       [3, 1, 2, 4],
       [5, 4, 1, 3],
       [4, 1, 3, 2],
       [4, 1, 5, 3],
       [4, 1, 5, 3],
       [1, 3, 2, 5],
       [3, 7, 2, 1],
       [5, 4, 3, 2],
       [7, 2, 1, 3],
       [7, 2, 1, 3],
       [3, 4, 7, 1],
       [3, 1, 2, 4],
       [1, 4, 3, 2],
       [2, 5, 1, 3],
       [6, 2, 3, 1],
       [1, 3, 2, 5],
       [5, 4, 1, 3],
       [2, 7, 5, 4],
       [3, 7, 2, 1],
       [2, 5, 1, 3],
       [3, 5, 1, 2],
       [3, 4, 7, 1],
       [1, 2, 3, 5]])

In [31]:
y_train

array([5, 2, 1, 1, 4, 1, 5, 3, 1, 3, 4, 5, 4, 4, 1, 5, 3, 1, 3, 4, 4, 5,
       1, 1, 3, 3, 4, 1, 4, 2, 3, 3, 3, 3, 1, 3, 1, 3, 4, 3, 1, 1, 1, 1,
       3, 1, 3, 3, 1, 1, 3, 1, 3, 1, 2, 1, 5, 1, 1, 3, 2, 4, 3, 1, 4, 5,
       3, 5, 1, 1, 1, 3, 3, 5, 5, 1, 1, 1, 3, 5, 1, 1, 4])

In [32]:
y_test

array([3, 1, 5, 5, 1, 3, 4, 4, 4, 4, 5, 1, 2, 1, 1, 1, 3, 2, 3, 3, 5, 4,
       4, 1, 3, 1, 1, 1])

In [33]:
clf = KNeighborsClassifier(n_neighbors=3)

In [34]:
clf.fit(X_train, y_train)
clf.fit(X_test, y_test)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=3, p=2,
           weights='uniform')

In [35]:
acc_train = clf.score(X_train, y_train)
acc_test = clf.score(X_test, y_test)

In [40]:
print("Training set accuracy: {:.2f}".format(acc_train))  
print("Test set accuracy: {:.2f}".format(acc_test))

Training set accuracy: 0.70
Test set accuracy: 0.71


In [41]:
print("New prediction:", list(mappings.keys())[list(mappings.values()).index(clf.predict([[mappings['England'],mappings['India'],mappings['Australia'],mappings['South Africa']]]))])

New prediction: England
